#!/bin/bash
# Script for testing fresh build of CodeTex with TeX.
echo "------------------------------------------------------------"
echo "Testing script for CodeTex"
echo "------------------------------------------------------------"

# Building procedure
echo "+ Building CodeTex..."
cd ..
mvn clean package assembly:single #appassembler:assemble

if [ "$?" != "0" ]; then
	echo "ERROR: There was problem with building CodeTex."
	exit 1
fi

# Testing procedure
echo "+ Starting application with sample tex file."
cd target
java -jar CodeTeX-jar-with-dependencies.jar -o ../test/temp.tex ../test/test.tex

if [ "$?" != "0" ]; then
	echo "ERROR: There was problem with application."
	exit 1
fi

# TeX procedure
cd ../test
echo "+ Compiling created file with pdfcsplain."
pdfcsplain temp.tex

echo "------------------------------------------------------------"
echo "Testing CodeTex complete!"
echo "------------------------------------------------------------"
